"""
Plugin Scanner

Reads REAPER's VST and AU plugin cache files and updates plugins.json
with exact plugin names ready for track_fx_add_by_name.
"""

import json
import platform
from pathlib import Path


def _reaper_config_dir() -> Path:
    system = platform.system()
    if system == "Darwin":
        return Path.home() / "Library" / "Application Support" / "REAPER"
    elif system == "Windows":
        import os
        return Path(os.environ.get("APPDATA", Path.home())) / "REAPER"
    else:
        return Path.home() / ".config" / "REAPER"


def _parse_vst_cache(ini_path: Path) -> tuple[list, list]:
    """Parse reaper-vstplugins_arm64.ini into (instruments, effects) lists."""
    instruments = []
    effects = []

    if not ini_path.exists():
        return instruments, effects

    for line in ini_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("[") or "=" not in line:
            continue

        filename, _, value = line.partition("=")
        filename = filename.lower()

        # Determine VST type from file extension
        if ".vst3" in filename:
            vst_type = "VST3"
        elif ".vst" in filename:
            vst_type = "VST"
        else:
            continue

        # Extract plugin name — always the last comma-separated segment
        name_part = value.split(",")[-1]
        is_instrument = "!!!VSTi" in name_part
        name = name_part.replace("!!!VSTi", "").strip()

        if not name:
            continue

        if is_instrument:
            prefix = "VST3i" if vst_type == "VST3" else "VSTi"
            instruments.append(f"{prefix}: {name}")
        else:
            prefix = "VST3" if vst_type == "VST3" else "VST"
            effects.append(f"{prefix}: {name}")

    return instruments, effects


def _parse_au_cache(ini_path: Path) -> tuple[list, list]:
    """Parse reaper-auplugins_arm64.ini into (instruments, effects) lists."""
    instruments = []
    effects = []

    if not ini_path.exists():
        return instruments, effects

    for line in ini_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("[") or "=" not in line:
            continue

        name, _, value = line.partition("=")
        name = name.strip()
        value = value.strip()

        if value == "<inst>":
            instruments.append(f"AUi: {name}")
        elif value == "<!inst>":
            effects.append(f"AU: {name}")

    return instruments, effects


def scan_plugins(plugins_json_path: Path = None) -> dict:
    """
    Scan REAPER's plugin cache and update plugins.json.

    Returns a summary dict with counts and the full lists.
    """
    config_dir = _reaper_config_dir()

    # Find the right INI files (arm64 on Apple Silicon, otherwise generic)
    vst_candidates = [
        config_dir / "reaper-vstplugins_arm64.ini",
        config_dir / "reaper-vstplugins64.ini",
        config_dir / "reaper-vstplugins.ini",
    ]
    au_candidates = [
        config_dir / "reaper-auplugins_arm64.ini",
        config_dir / "reaper-auplugins_arm64-bc.ini",
        config_dir / "reaper-auplugins.ini",
    ]

    all_instruments = []
    all_effects = []

    for vst_path in vst_candidates:
        if vst_path.exists():
            instr, fx = _parse_vst_cache(vst_path)
            all_instruments.extend(instr)
            all_effects.extend(fx)
            break

    for au_path in au_candidates:
        if au_path.exists():
            instr, fx = _parse_au_cache(au_path)
            all_instruments.extend(instr)
            all_effects.extend(fx)
            break

    # Deduplicate while preserving order
    seen = set()
    instruments = []
    for p in all_instruments:
        if p not in seen:
            seen.add(p)
            instruments.append(p)

    seen = set()
    effects = []
    for p in all_effects:
        if p not in seen:
            seen.add(p)
            effects.append(p)

    # Sort alphabetically
    instruments.sort()
    effects.sort()

    result = {
        "instruments": instruments,
        "effects": effects,
        "_instructions": (
            "Auto-generated by plugin_scanner.py. "
            "Re-run scan after installing new plugins."
        ),
    }

    # Save to plugins.json
    if plugins_json_path is None:
        plugins_json_path = Path(__file__).parent / "plugins.json"

    plugins_json_path.write_text(json.dumps(result, indent=2))

    return {
        "ok": True,
        "instruments_found": len(instruments),
        "effects_found": len(effects),
        "instruments": instruments,
        "effects": effects,
    }


if __name__ == "__main__":
    result = scan_plugins()
    print(f"Found {result['instruments_found']} instruments, {result['effects_found']} effects")
    print("\nInstruments:")
    for p in result["instruments"]:
        print(f"  {p}")
    print("\nEffects:")
    for p in result["effects"]:
        print(f"  {p}")
